In [7]:
# En Pandas existen dos estructuras de datos:
# Importamos pandas con el alias pd
import pandas as pd

# SERIES: Se componen de manera unidimensional a traves de filas (SERIES)
ventas = pd.Series([100, 200, 300, 400, 500])
ventas.index = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo']
print(ventas)

# DATAFRAMES: Se componen de manera bidimensional a traves de filas y columnas (DATAFRAMES)
ventas1 = pd.DataFrame({
    "Meses": ["Enero", "Febrero", "Marzo", "Abril"],
    "Dias": [31, 28, 31, 30]
})
ventas1.index = ["1","2", "3", "4"]

ventas1.head()

Enero      100
Febrero    200
Marzo      300
Abril      400
Mayo       500
dtype: int64

     Meses  Dias
1    Enero    31
2  Febrero    28
3    Marzo    31
4    Abril    30

In [5]:
# En Pandas existen dos estructuras de datos:
# Importamos pandas con el alias pd
import pandas as pd

# SERIES: Se componen de manera unidimensional a traves de filas (SERIES)
ventas = pd.Series([100, 200, 300, 400, 500])
print(ventas)

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [8]:
# En Pandas existen dos estructuras de datos:
# Importamos pandas con el alias pd
import pandas as pd

# SERIES: Se componen de manera unidimensional a traves de filas (SERIES)
ventas = pd.Series([100, 200, 300, 400, 500], index=['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'])
# print(ventas)

# DATAFRAMES: Se componen de manera bidimensional a traves de filas y columnas (DATAFRAMES)
datos = {
    "producto": [
        "Notebook",
        "Mouse",
        "Teclado"
    ],
    "precio": [
        850000,
        15000,
        35000,
    ],
    "cantidad": [
        2,
        5,
        3
    ]
}

df = pd.DataFrame(datos, index=["1", "2", "3"])
print(df)
df.head()  # Muestra las primeras 5 filas del DataFrame

   producto  precio  cantidad
1  Notebook  850000         2
2     Mouse   15000         5
3   Teclado   35000         3

   producto  precio  cantidad
1  Notebook  850000         2
2     Mouse   15000         5
3   Teclado   35000         3